
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS User (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Mail TEXT NOT NULL UNIQUE,
    Username TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Locked INTEGER DEFAULT 0,
    Permission TEXT DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS Post (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    Private INTEGER DEFAULT 0,
    Description TEXT,
    Weather TEXT NOT NULL,
    Temperature INT NOT NULL,
    Adress TEXT NOT NULL,
    Type TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Image (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PostID INTEGER NOT NULL,
    FilePath TEXT NOT NULL,
    FOREIGN KEY (PostID) REFERENCES Post(ID) ON DELETE CASCADE
);
